"""Tests for ADR-0010 Decision 2/5/6/7 -- direction representation.

The mechanism itself (`out_edges`/`in_edges` graph traversal indices,
generated by a runtime graph compiler) is not this module's to implement --
`OKF-Knowledge-Graph-Specification.md:241`'s Adjacency Derivation section
describes a compiler behaviour, and no such compiler exists yet in
`cric-core`. What this module implements is the *testable requirement* that
behaviour rests on: which predicates have a registered inverse, and
detecting when both directions of the same fact have been declared
independently -- the condition the compiler must treat as a duplicate edge.
"""

import pytest

from cric_core.relationships import (
    KNOWN_INVERSE_PAIRS,
    InverseNotRegistered,
    RelationshipEdge,
    RelationshipPredicate,
    detect_duplicate_inverse_declarations,
    registered_inverse,
)

# --- KNOWN_INVERSE_PAIRS: exactly the three corpus-evidenced pairs -----------


def test_known_inverse_pairs_is_exactly_the_three_corpus_evidenced_pairs():
    # Decision 5: not a claim that nothing else has an inverse -- only that
    # nothing else is *registered* as one in the ratified sources.
    assert KNOWN_INVERSE_PAIRS == frozenset(
        {
            (RelationshipPredicate.SUPPORTS, RelationshipPredicate.SUPPORTED_BY),
            (RelationshipPredicate.SUPERSEDES, RelationshipPredicate.SUPERSEDED_BY),
            (RelationshipPredicate.FEEDS, RelationshipPredicate.FED_BY),
        }
    )


@pytest.mark.parametrize(
    ("forward", "backward"),
    [
        (RelationshipPredicate.SUPPORTS, RelationshipPredicate.SUPPORTED_BY),
        (RelationshipPredicate.SUPERSEDES, RelationshipPredicate.SUPERSEDED_BY),
        (RelationshipPredicate.FEEDS, RelationshipPredicate.FED_BY),
    ],
)
def test_registered_inverse_is_symmetric(forward, backward):
    assert registered_inverse(forward) == backward
    assert registered_inverse(backward) == forward


def test_registered_inverse_raises_for_a_predicate_with_no_registered_pair():
    with pytest.raises(InverseNotRegistered):
        registered_inverse(RelationshipPredicate.CONTRADICTS)


# --- Decision 7: consistent_with / inconsistent_with are never paired -------


def test_consistent_with_and_inconsistent_with_are_not_paired_with_each_other():
    with pytest.raises(InverseNotRegistered):
        registered_inverse(RelationshipPredicate.CONSISTENT_WITH)
    with pytest.raises(InverseNotRegistered):
        registered_inverse(RelationshipPredicate.INCONSISTENT_WITH)

    pair = (RelationshipPredicate.CONSISTENT_WITH, RelationshipPredicate.INCONSISTENT_WITH)
    assert pair not in KNOWN_INVERSE_PAIRS
    assert tuple(reversed(pair)) not in KNOWN_INVERSE_PAIRS


# --- detect_duplicate_inverse_declarations -----------------------------------


def test_detects_a_duplicate_declared_in_both_directions():
    edges = [
        RelationshipEdge("A", RelationshipPredicate.SUPPORTS, "B"),
        RelationshipEdge("B", RelationshipPredicate.SUPPORTED_BY, "A"),
    ]

    duplicates = detect_duplicate_inverse_declarations(edges)

    assert len(duplicates) == 1
    flattened = {edge for pair in duplicates for edge in pair}
    assert flattened == set(edges)


def test_a_single_direction_declaration_is_not_flagged():
    edges = [RelationshipEdge("A", RelationshipPredicate.SUPPORTS, "B")]

    assert detect_duplicate_inverse_declarations(edges) == frozenset()


def test_unrelated_edges_sharing_a_node_are_not_flagged():
    # Same two nodes, but not an inverse pair of each other -- must not
    # false-positive just because A and B appear in both edges.
    edges = [
        RelationshipEdge("A", RelationshipPredicate.SUPPORTS, "B"),
        RelationshipEdge("B", RelationshipPredicate.CONTRADICTS, "A"),
    ]

    assert detect_duplicate_inverse_declarations(edges) == frozenset()


def test_a_predicate_with_no_registered_inverse_can_never_be_flagged():
    # By construction: with no second vocabulary word, there is nothing to
    # declare the duplicate with. Declaring the same predicate twice in the
    # same direction is not what this function checks -- it checks for the
    # *inverse-direction* duplicate.
    edges = [
        RelationshipEdge("A", RelationshipPredicate.CONTRADICTS, "B"),
        RelationshipEdge("B", RelationshipPredicate.CONTRADICTS, "A"),
    ]

    assert detect_duplicate_inverse_declarations(edges) == frozenset()


def test_three_way_chain_only_flags_the_actual_inverse_pair():
    edges = [
        RelationshipEdge("A", RelationshipPredicate.FEEDS, "B"),
        RelationshipEdge("B", RelationshipPredicate.FED_BY, "A"),
        RelationshipEdge("B", RelationshipPredicate.FEEDS, "C"),
    ]

    duplicates = detect_duplicate_inverse_declarations(edges)

    assert len(duplicates) == 1
    flattened = {edge for pair in duplicates for edge in pair}
    assert flattened == {edges[0], edges[1]}
