"""Generate README's build-status block from the live repository tree.

Implements ADR-0008 (`decisions/0008-ci-generated-build-status.md`, WP-33a):
build status is CI-generated, never hand-typed, and fails loudly on anything
it cannot derive mechanically rather than emitting a default.

Usage:
    python scripts/generate_build_status.py [--check] [--readme-path PATH]

With no flags, regenerates the block and rewrites it in place between the
existing `BUILD-STATUS` markers in the target file (default: `README.md`,
relative to the current working directory). If both markers are not present
in the target file, this fails loudly rather than inserting them -- placing
the markers themselves is a sibling work package's job, not this script's.

With `--check`, computes what the block would be, compares it to what is
currently between the markers, and exits 0 if identical or 1 (printing a
unified diff to stderr) if not, without writing anything.

Every derivation below either produces a real value or raises `RuntimeError`
naming exactly what it could not derive. There is no default/placeholder
path: per ADR-0008, a generated block that doesn't exist yet is preferable
to one that silently guesses.

This script must be invoked with the current working directory set to the
repository root (the same convention CI's `test` job and every other command
in this repository use -- see `CLAUDE.md` SS7). It intentionally does not
add any `env -u PYTHONHOME -u PYTHONPATH` prefixing itself: that is a
dev-host-only artefact the *caller* is responsible for on this machine, and
must never leak into `ci.yml` or this script (see ADR-0008 / CLAUDE.md SS7).
"""

from __future__ import annotations

import argparse
import difflib
import re
import subprocess
import sys
from pathlib import Path

MARKER_START = "<!-- BUILD-STATUS:START -->"
MARKER_END = "<!-- BUILD-STATUS:END -->"

_SEQUENCE_DOC = "docs/CRIC-PRD-v0.1/CRIC-Repository-Dependency-and-Implementation-Sequence.md"
_FREEZE_POINTS_HEADING_RE = re.compile(r"^##\s+Architecture Freeze Points\s*$")
_LIST_ITEM_RE = re.compile(r"^\d+\.")

_STATUS_LINE_RE = re.compile(r"^- \*\*Status:\*\*.*$", re.MULTILINE)
_ADR_TITLE_RE = re.compile(r"^# ADR-\d+:.*$", re.MULTILINE)
_FREEZE_POINT_NUMBERS_RE = re.compile(r"Freeze Points?\s+([0-9][0-9,+\s]*?)\s*[—-]")

_PASSED_COUNT_RE = re.compile(r"(\d+) passed")

TEMPLATE = """\
<!-- BUILD-STATUS:START -->
<!-- Generated by `python scripts/generate_build_status.py` -- do not hand-edit
     between these markers. CI's `test` job fails if this drifts from what the
     generator derives from the live tree. See decisions/0008. -->
- **{test_count} tests passing** (full suite, `pytest`, no path filter).
- **{ratified_count} of {total_fp} Architecture Freeze Points ratified** (a `decisions/`
  entry whose Status line reads "Architecture Freeze Point").
- **{module_count} module(s) shipped** under `src/cric_core/`: {module_list}.
<!-- BUILD-STATUS:END -->"""


def derive_test_count(repo_root: Path) -> int:
    """Run the real test suite and parse the passed count.

    Raises RuntimeError (naming `{test_count}`) if the subprocess exits
    non-zero or if no `<N> passed` summary line is found -- never returns a
    placeholder.
    """
    result = subprocess.run(
        [sys.executable, "-m", "pytest", "-q"],
        cwd=repo_root,
        capture_output=True,
        text=True,
        check=False,
    )
    if result.returncode != 0:
        raise RuntimeError(
            "could not derive {test_count}: `python -m pytest -q` exited "
            f"{result.returncode} (expected 0).\n--- stdout ---\n{result.stdout}"
            f"\n--- stderr ---\n{result.stderr}"
        )
    match = _PASSED_COUNT_RE.search(result.stdout)
    if match is None:
        raise RuntimeError(
            "could not derive {test_count}: no '<N> passed' summary found in "
            f"`pytest -q` stdout:\n{result.stdout}"
        )
    return int(match.group(1))


def derive_total_freeze_points(repo_root: Path) -> int:
    """Count the numbered Architecture Freeze Points list in the sequence doc.

    Raises RuntimeError (naming `{total_fp}`) if the heading is missing or if
    zero list items are found under it -- never returns 0 silently.
    """
    path = repo_root / _SEQUENCE_DOC
    try:
        text = path.read_text(encoding="utf-8")
    except OSError as exc:
        raise RuntimeError(f"could not derive {{total_fp}}: could not read {path}: {exc}") from exc

    lines = text.splitlines()
    heading_idx = next(
        (i for i, line in enumerate(lines) if _FREEZE_POINTS_HEADING_RE.match(line)),
        None,
    )
    if heading_idx is None:
        raise RuntimeError(
            "could not derive {total_fp}: no '## Architecture Freeze Points' heading "
            f"found in {path}"
        )

    count = 0
    started = False
    i = heading_idx + 1
    while i < len(lines):
        line = lines[i]
        if line.startswith("## "):
            break
        if _LIST_ITEM_RE.match(line):
            count += 1
            started = True
            i += 1
            continue
        if line.strip() == "":
            j = i + 1
            while j < len(lines) and lines[j].strip() == "":
                j += 1
            if j < len(lines) and _LIST_ITEM_RE.match(lines[j]):
                i = j
                continue
            if started:
                break
            i = j
            continue
        if started:
            break
        i += 1

    if count == 0:
        raise RuntimeError(
            "could not derive {total_fp}: found no numbered list items under the "
            f"'## Architecture Freeze Points' heading in {path} -- the document's "
            "shape may have changed"
        )
    return count


def derive_ratified_freeze_points(repo_root: Path) -> set[int]:
    """Scan decisions/*.md for ratified Architecture Freeze Points.

    For each decision file, look at the first `^- **Status:**` line only. If
    it contains "Architecture Freeze Point" (a substring match, so it also
    catches the plural "Architecture Freeze Points"), extract the Freeze
    Point number(s) named in the ADR's title line and union them into the
    ratified set.

    Raises RuntimeError if a Status line names an Architecture Freeze Point
    but the title yields zero extractable numbers -- that would silently
    undercount rather than fail loudly.
    """
    decisions_dir = repo_root / "decisions"
    ratified: set[int] = set()
    for path in sorted(decisions_dir.glob("*.md")):
        text = path.read_text(encoding="utf-8")
        status_match = _STATUS_LINE_RE.search(text)
        if status_match is None:
            continue
        status_line = status_match.group(0)
        if "Architecture Freeze Point" not in status_line:
            continue

        title_match = _ADR_TITLE_RE.search(text)
        if title_match is None:
            raise RuntimeError(
                f"could not derive {{ratified_count}}: {path} has a Status line naming "
                "an Architecture Freeze Point but no '# ADR-NNNN: ...' title line"
            )
        title_line = title_match.group(0)

        fp_match = _FREEZE_POINT_NUMBERS_RE.search(title_line)
        if fp_match is None:
            raise RuntimeError(
                f"could not derive {{ratified_count}}: {path}'s Status line names an "
                f"Architecture Freeze Point but its title {title_line!r} yields no "
                "extractable Freeze Point number(s)"
            )
        numbers = re.findall(r"\d+", fp_match.group(1))
        if not numbers:
            raise RuntimeError(
                f"could not derive {{ratified_count}}: {path}'s title {title_line!r} "
                "matched the Freeze Point pattern but contained no digits"
            )
        ratified.update(int(n) for n in numbers)
    return ratified


def derive_modules(repo_root: Path) -> list[str]:
    """List shipped `src/cric_core/` subpackages (dirs with an `__init__.py`).

    An empty result is legitimate (write `0` / `none yet`), not an error --
    only IO/parse failures raise.
    """
    package_dir = repo_root / "src" / "cric_core"
    return sorted(
        p.name for p in package_dir.iterdir() if p.is_dir() and (p / "__init__.py").exists()
    )


def generate_block(repo_root: Path) -> str:
    """Derive every value and render the exact BUILD-STATUS block text."""
    test_count = derive_test_count(repo_root)
    total_fp = derive_total_freeze_points(repo_root)
    ratified_count = len(derive_ratified_freeze_points(repo_root))
    modules = derive_modules(repo_root)
    module_count = len(modules)
    module_list = ", ".join(f"`{name}`" for name in modules) if modules else "none yet"

    return TEMPLATE.format(
        test_count=test_count,
        ratified_count=ratified_count,
        total_fp=total_fp,
        module_count=module_count,
        module_list=module_list,
    )


def _find_markers(content: str) -> tuple[int, int]:
    start_idx = content.find(MARKER_START)
    end_idx = content.find(MARKER_END)
    if start_idx == -1 or end_idx == -1:
        raise RuntimeError(
            f"target file has no {MARKER_START!r} / {MARKER_END!r} marker pair -- "
            "this script fails loudly rather than inserting markers itself "
            "(placing the markers is a sibling work package's job, see ADR-0008)"
        )
    if end_idx < start_idx:
        raise RuntimeError(
            f"target file has {MARKER_END!r} before {MARKER_START!r} -- malformed marker pair"
        )
    return start_idx, end_idx


def extract_block(content: str) -> str:
    """Return the current text between (and including) the markers."""
    start_idx, end_idx = _find_markers(content)
    return content[start_idx : end_idx + len(MARKER_END)]


def apply_block(content: str, new_block: str) -> str:
    """Return `content` with the marker-delimited block replaced by `new_block`.

    Everything outside the markers is left byte-for-byte untouched.
    """
    start_idx, end_idx = _find_markers(content)
    return content[:start_idx] + new_block + content[end_idx + len(MARKER_END) :]


def main(argv: list[str] | None = None) -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="don't write; exit 1 with a diff on stderr if the block would change",
    )
    parser.add_argument(
        "--readme-path",
        default="README.md",
        help="target file, relative to CWD (default: README.md)",
    )
    args = parser.parse_args(argv)

    repo_root = Path.cwd()
    readme_path = Path(args.readme_path)

    try:
        new_block = generate_block(repo_root)
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    try:
        content = readme_path.read_text(encoding="utf-8")
    except OSError as exc:
        print(f"error: could not read {readme_path}: {exc}", file=sys.stderr)
        return 1

    if args.check:
        try:
            current_block = extract_block(content)
        except RuntimeError as exc:
            print(f"error: {exc}", file=sys.stderr)
            return 1
        if current_block == new_block:
            return 0
        diff = difflib.unified_diff(
            current_block.splitlines(keepends=True),
            new_block.splitlines(keepends=True),
            fromfile=f"{readme_path} (current)",
            tofile=f"{readme_path} (generated)",
        )
        sys.stderr.writelines(diff)
        return 1

    try:
        updated_content = apply_block(content, new_block)
    except RuntimeError as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    readme_path.write_text(updated_content, encoding="utf-8")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
